### ISSUE TITLE
Is there a shortcut for translating words under the pointer?

### ISSUE THREAD

**Issue by limeng233** [VincentCordobes/vim-translate#10]

**Comment by VincentCordobes** [comment]
Currently there is no built-in way to do it but a simple trick would be with the `TranslateVisual` command.

For example you can create a mapping like so:
```
nnoremap <silent> <leader>tw viw :TranslateVisual<CR>
```

Tell me if that's ok for you @limeng233  😉

**Comment by limeng233** [comment]
Thank you, your answer solved my problem perfectly.  @VincentCordobes
