### ISSUE TITLE
Old type of register 'a' is forgotten 

### ISSUE THREAD

**Issue by perelo** [VincentCordobes/vim-translate#12]
Hi!

Great plugin! I love the minimalism :1st_place_medal:, sitting on the shoulders of giants.

Thanks to the wierdness of vim, in `autoload/translate.vim`, the backup mechanism for register `a` using `=` doesn't remember the type (`v`, `V` or `^V`) of `a`. To see it, if `a` initially contain visual-block-coppied text, after translating something, `"ap` will put `a` as if it was a set of lines.

To fix this, we could replace
```
  let l:backup = @a
" and
  let @a = l:backup
```
by
```
  let l:regtype = getregtype('a')
  let l:regtext = getreg('a')
" and
  call setreg('a', l:regtext, l:regtype)
```
respectively.

Otherwise, I think it could be nice to have operator mappings (as `<Plug>` mappings) to translate text with operators. e.g it would allow something like `<leader>tiw` to translate the current word as in #10, or `<leader>t)` to translate until the end of the sentence.

Would you mind PR(s) ?

Regards

**Comment by VincentCordobes** [comment]
Hey, 
Thank you @perelo, these are excellent ideas.
Feel free to send a PR(s) 🙂
