### ISSUE TITLE
Support visual mode

### ISSUE THREAD

**Issue by tracyone** [VincentCordobes/vim-translate#3]

**Comment by soywod** [comment]
An other repo with a different approach allows you to use visual selection. But it's not using buffer, it's translating directly the selection. Have a look : https://github.com/soywod/vim-translate. Maybe a PR here could be interesting ?

**Comment by soywod** [comment]
You can have a look to https://github.com/soywod/vim-translate, the selection has been implemented. But the selection is replaced instead of placed in a buffer, a PR here could be interesting !

**Comment by soywod** [comment]
Feature merged :champagne:
