### ISSUE TITLE
Not working when vim/nvim is restarted?

### ISSUE THREAD

**Issue by aurelg** [VincentCordobes/vim-translate#8]
Thanks a lot for this nice plugin. I tried it with `vim` (8.1.542) and `neovim` (0.3.1) (both using `vim-plug`). The `Translate` command is available and works as expected once the plugin is installed with `PlugInstall`. Unfortunately, if `vim` or `nvim` is restarted, the `Translate` command is not available unless `vim-translate` is reinstalled. I must be missing something?

**Comment by soywod** [comment]
Could you share your `.vimrc`?

**Comment by VincentCordobes** [comment]
Can you try to put `Plug 'VincentCordobes/vim-translate'` before  `call plug#end()` ? 

As `call plug#end()`  is responsible for updating runtimepath, it has to be called after all the`Plug ".."`
(you might have the same issue with `'wannesm/wmgraphviz.vim'`) @aurelg

**Comment by aurelg** [comment]
Thanks a lot, my mistake, it now works perfectly. I wish I haven't posted such a stupid question. :-/

**Comment by VincentCordobes** [comment]
Great 🙂
