### ISSUE TITLE
Can I use vim-translate in gvim under window with cygwin and translate-shell?

### ISSUE THREAD

**Issue by ChenWeird** [VincentCordobes/vim-translate#9]
Translate-shell can run under Windows (through WSL, Cygwin, or MSYS2).
And there is also gvim under windows.

Can I use vim-translate in gvim under window with WSL or cygwin and translate-shell?

**Comment by VincentCordobes** [comment]
Yes I suppose (I don't see any reason why it wouldn't work)
I'll try later in the day

**Comment by ChenWeird** [comment]
I've installed GVIM 8.1.1 with vim-translate under win10.
I've also installed Translate Shell in Cygwin64 under win10, and it work well.

I do not know how to run Translate Shell in GVIM, thanks!

**Comment by VincentCordobes** [comment]
Ok 👍 You might want to tell GVIM which shell—cygwin or wsl—to use when executing an external cmd (like `trans`)  Maybe `set shell` can help. let me know!

**Comment by ChenWeird** [comment]
I've reinstall WSL and Translate Shell, and add the following code to vimrc:
```
if has("windows")
    set shell=C:\Windows\Sysnative\wsl.exe
    set shellpipe=|
    set shellredir=>
    set shellcmdflag=
endif
```
Now I can run Translate Shell command such as `:!trans word` , and it can pop up shell to work well.
But vim-translate can not work, what should I do?
`translate-shell not found. please install it.`

**Comment by ChenWeird** [comment]
reference:

https://vi.stackexchange.com/questions/16386/how-to-use-wsls-bash-shell-as-default-terminal-of-gvim-windows-10

**Comment by VincentCordobes** [comment]
Indeed @ChenWeird I haven't managed to make the `executable()` check work on win.
So I disabled it for now. Can you try with the `win-compat` branch?`
```
Plug 'VincentCordobes/vim-translate', {'commit': 'win-compat' }
```


**Note:** Also what you may want in your vimrc is `if has('win32')` instead of `if has("windows")` cuz `windows` means something else:
> Compiled with support for more than one window

**Comment by limeng233** [comment]
How to customize the words under the default translation pointer?
